name: main

on:
  workflow_dispatch:
  # Run at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.8.0
      - run: npm ci
      - name: Generate quote
        # Chạy script to change README.md
        run: npm run generate
      - name: Update README.md
        # Push file README.md to github
        run: |
          git config --global user.email "kelvin.nguyen@bookwell.com.au"
          git config --global user.name "Kelvin Nguyen"
          git add .
          git commit -m "Updated README.md" || echo "No changes to commit"
          git push
